# Generated by Django 5.2.17 on 2026-09-02 10:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('college', models.CharField(max_length=200)),
                ('member1_name', models.CharField(max_length=100)),
                ('member1_mobile', models.CharField(max_length=15)),
                ('member1_email', models.EmailField(max_length=150)),
                ('member2_name', models.CharField(max_length=100)),
                ('member2_mobile', models.CharField(max_length=15)),
                ('member2_email', models.EmailField(max_length=150)),
                ('pin_hash', models.CharField(max_length=128)),
                ('current_stage', models.IntegerField(default=1)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('hint_count', models.IntegerField(default=0)),
                ('penalty_seconds', models.IntegerField(default=0)),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('submitted_key', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_logs', to='hunt.team')),
            ],
        ),
        migrations.CreateModel(
            name='HintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('penalty_seconds', models.IntegerField(default=300)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_logs', to='hunt.team')),
            ],
        ),
    ]
