# Generated by Django 5.2.17 on 2026-09-02 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hintlog',
            name='hint_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submissionlog',
            name='points_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='stage_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hintlog',
            name='penalty_seconds',
            field=models.IntegerField(default=180),
        ),
    ]
